# Generated by Django 5.2.3 on 2025-06-16 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faq",
            options={"verbose_name": "FAQ", "verbose_name_plural": "FAQ"},
        ),
        migrations.CreateModel(
            name="StartMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_startmessages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Admin user who added this start message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Start message",
                "verbose_name_plural": "Start messages",
                "ordering": ["id"],
            },
        ),
    ]
