# Generated by Django 5.2.3 on 2025-06-19 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StartMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "message",
                    models.TextField(
                        help_text="Форматирование: *жирный* , _курсив_ , `моноширинный` , [ссылка](https://example.com)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_startmessages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Admin user who added this start message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Start message",
                "verbose_name_plural": "Start messages",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.TextField()),
                (
                    "text",
                    models.TextField(
                        help_text="Форматирование: *жирный* , _курсив_ , `моноширинный` , [ссылка](https://example.com)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageForTopic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="topic_images/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="images", to="content.topic"
                    ),
                ),
            ],
        ),
    ]
